name: Java CI with Ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print directory structure
      run: ls -R

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Check Ant version
      run: ant -version

    - name: Build project
      run: |
        cd ChatSystem
        ant build

    - name: Run Ant tests
      run: |
        cd ChatSystem
        ant test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ChatSystem/build/reports/

